#!/bin/sh
#Generate SSL certificates using OpenSSL
echo "Creating SSL certificates..."
chmod +x /Library/Application\ Support/iOSMB-Server/certs.sh
/Library/Application\ Support/iOSMB-Server/certs.sh 2>&1 > /dev/null

#Setup Daemon
chown root:wheel /Library/LaunchDaemons/com.enzodjabali.iosmb-server.plist
launchctl load /Library/LaunchDaemons/com.enzodjabali.iosmb-server.plist

#Restart IMAgent to handle new capabilities 
killall -9 imagent
